name: git
services:
  # Forgejo (Git Server)
  # https://forgejo.org/docs/next/admin/installation/
  forgejo:
    image: codeberg.org/forgejo/forgejo:14
    container_name: forgejo
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 127.0.0.1:${FORGEJO_HTTP_PORT}:3000
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - TZ=${TIMEZONE}
      # Database
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=${FORGEJO_DB_PASSWORD}
    volumes:
      - ${FORGEJO_DATA}:/data
    networks:
      - proxy_net
      - forgejo
    labels:
      - wud.watch=true
      - wud.trigger.docker.enable=false
  # PostgreSQL (Forgejo Database)
  db:
    image: postgres:14
    container_name: forgejo-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=${FORGEJO_DB_PASSWORD}
      - POSTGRES_DB=forgejo
    volumes:
      - ${FORGEJO_DB_DATA}:/var/lib/postgresql/data
    networks:
      - proxy_net
      - forgejo
    healthcheck:
      test: pg_isready -U forgejo
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    labels:
      - wud.watch=true
      - wud.trigger.docker.enable=false
networks:
  forgejo:
    internal: true
  proxy_net:
    external: true
