name: uptime

services:
  # Uptime Kuma (Uptime Monitoring)
  # https://uptimekuma.org/install-uptime-kuma-docker/
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "127.0.0.1:${UPTIME_PORT}:3001"
    environment:
      - TZ=${TIMEZONE}
      - UMASK=0022  # Set your file permissions manually
    volumes:
      - ${UPTIME_DATA}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_net
    labels:
      - wud.watch=true
      - wud.trigger.docker.enable=false

networks:
  proxy_net:
    external: true
