name: portainer
services:
  # Portainer (Docker Container Manager)
  # https://docs.portainer.io/start/install/server/docker/linux
  portainer:
    image: portainer/portainer-ee:sts
    container_name: portainer
    restart: unless-stopped
    ports:
      - 127.0.0.1:${PORTAINER_PORT}:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_DATA}:/data
    networks:
      - proxy_net
networks:
  proxy_net:
    external: true
